#! /usr/bin/env python
from time import strftime

img_version = strftime("%Y%m%d")
edition = "Plasma"
device = "vim4"
arch = "aarch64"  # aarch64, armv7h
img_name = "vim4-bredos-arm-plasma-v" + img_version
install_dir = "arch"
fs = "btrfs"  # ext4 or btrfs
img_type = "image"  # image (img.xz) or rootfs (tar.gz)
img_backend = "loop"  # loop or qemu-nbd

# If you use btrfs you need add `rootflags=subvol=@ rootfstype=btrfs`
# And remove `rootfstype=ext4`

cmdline = "console=ttyS0,921600 console=tty0 no_console_suspend earlycon=aml-uart,0xfe078000 xhci_hcd.quirks=0x800000 otg_device=1 irqchip.gicv3_pseudo_nmi=0 fan=auto consoleblank=0 loglevel=0 panic=10 rootwait rw init=/sbin/init rootflags=subvol=@ rootfstype=btrfs cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1 irqchip.gicv3_pseudo_nmi=0 switolb=1 coherent_pool=2M scsi_mod.scan=async scramble_reg=0xfe02e030 gamma=0 logo=osd0,loaded,0x3fdeec00 vout=1080p60hz,enable panel_type=mipi_0 hdmitx=,444,8bit hdmimode=1080p60hz hdmichecksum=0x6ea00000 frac_rate_policy=1 cvbsmode=576cvbs video_reverse=0 kvm-arm.mode=none init_on_alloc=0 nn_adj_vol=0 powermode=on lcd_ctrl=0x37000083 outputmode=1080p60hz hdmitx=,444,8bit panel1_type=vbyone_1 lcd1_ctrl=0x00000000 panel2_type=lvds_1 lcd2_ctrl=0x00000000"

configtxt = """label BredOS ARM
    kernel /vmlinuz-linux-vim4
    initrd /initramfs-linux-vim4.img
    fdtdir /dtbs
"""

partition_table = lambda img_size, fs: {
    "boot": ["16M", "150M", "134M", "fat32"],
    "primary": ["150M", "100%", str(int(img_size / 1000) - 150) + "M", fs],
}

partition_extras = lambda config_dir, disk: [
    ["mkfs.fat", "-v", "-F32", "-n", "BOOT", disk + "p1"],
]

uboot = lambda config_dir, disk: [
    ["dd", "if=" + config_dir + "/u-boot.bin.sd.bin.signed", "of=" + disk, "conv=fsync,notrunc", "bs=512", "seek=1"],
    ["dd", "if=" + config_dir + "/u-boot.bin.sd.bin.signed", "of=" + disk, "conv=fsync,notrunc", "bs=512", "skip=1", "seek=1"],
]

perms = {
    "/etc/": ["0", "0", "755"],
    "/usr/bin/resizefs": ["0", "0", "755"],
    "/usr/bin/zswap-arm-ctrl": ["0", "0", "755"],
    "/usr/bin/oemcleanup": ["0", "0", "755"],
    "/etc/polkit-1/rules.d": ["0", "0", "750"],
    "/etc/sudoers.d": ["0", "0", "750"],
    "/usr/lib": ["0", "0", "755"],
    "/usr/bin": ["0", "0", "755"],
    "/usr": ["0", "0", "755"],
    "/home/bred/.config/autostart/org.bredos.bakery.desktop": ["1001", "1001", "755"],
    "/home/bred/Desktop/org.bredos.bakery.desktop": ["1001", "1001", "755"],
    "/home/bred/": ["1001", "1001", "750"],
    "/home": ["0", "0", "755"],
}
