#! /usr/bin/env python
from time import strftime

img_version = strftime("%Y%m%d")
edition = "Cinnamon"
device = "edge2"
arch = "aarch64"  # aarch64, armv7h
img_name = "edge2-bredos-arm-cinnamon-v" + img_version
install_dir = "arch"
fs = "btrfs"  # ext4 or btrfs
img_type = "image"  # image (img.xz) 
img_backend = "loop"  # loop or qemu-nbd

# If you use btrfs you need add `rootflags=subvol=@ rootfstype=btrfs`
# And remove `rootfstype=ext4`

cmdline = "${bootargs} console=ttyFIQ0 console=tty0 irqchip.gicv3_pseudo_nmi=0 lcd_panel=${lcd_panel} fan=${fan_mode} consoleblank=0 loglevel=3 panic=10 rootwait rw init=/sbin/init rootfstype=btrfs rootflags=subvol=@ cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1 irqchip.gicv3_pseudo_nmi=0 switolb=1 coherent_pool=2M"

configtxt = """label BredOS ARM
    kernel /vmlinuz-linux-rockchip
    initrd /initramfs-linux-rockchip.img
    devicetreedir /dtbs/
    fdt /dtbs/rockchip/rk3588s-khadas-edge2.dtb

"""

partition_table = lambda img_size, fs: {
    "boot": ["0%", "150M", "150M", "fat32"],
    "primary": ["150M", "100%", str(int(img_size / 1000) - 150) + "M", fs],
}

partition_suffix = lambda config_dir, disk: [
    ["mkfs.fat", "-v", "-F32", "-n", "BOOT", disk + "p1"],
]

perms = {
    "/etc/": ["0", "0", "755"],
    "/usr/bin/resizefs": ["0", "0", "755"],
    "/usr/bin/zswap-arm-ctrl": ["0", "0", "755"],
    "/usr/bin/pacman-init": ["0", "0", "755"],
    "/usr/bin/oemcleanup": ["0", "0", "755"],
    "/etc/polkit-1/rules.d": ["0", "0", "750"],
    "/etc/sudoers.d": ["0", "0", "750"],
    "/usr/lib": ["0", "0", "755"],
    "/usr/bin": ["0", "0", "755"],
    "/usr": ["0", "0", "755"],
    "/home/bred/.config/autostart/org.bredos.bakery.desktop": ["1001", "1001", "755"],
    "/home/bred/Desktop/org.bredos.bakery.desktop": ["1001", "1001", "755"],
    "/home/bred/": ["1001", "1001", "750"],
    "/home": ["0", "0", "755"],
}
