#! /usr/bin/env python
from time import strftime

img_version = strftime("%Y-%m-%d")
edition = ""
arch = "aarch64"  # aarch64, armv7h, riscv64
img_name = "BredOS-ARM-rpi-" + img_version
install_dir = "arch"
fs = "btrfs"  # ext4 or btrfs
img_type = "image"  # image (img.xz) or rootfs (tar.gz)
img_backend = "loop"  # loop or qemu-nbd

# If you use btrfs you need add `rootflags=subvol=@ rootfstype=btrfs`
# And remove `rootfstype=ext4`

cmdline = "rootflags=subvol=@ rootfstype=btrfs console=tty1 consoleblank=0 loglevel=0 panic=10 rootwait rw init=/sbin/init cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1 irqchip.gicv3_pseudo_nmi=0 switolb=1 coherent_pool=2M"

configtxt = """label BredOS ARM
    kernel /vmlinux-rockchip64
    initrd /initramfs-linux-rockchip64.img
    devicetreedir /dtbs/

"""

partition_table = lambda img_size, fs: {
    "boot": ["0%", "150M", "150M", "fat32"],
    "primary": ["150M", "100%", str(int(img_size / 1000) - 150) + "M", fs],
}

partition_suffix = lambda config_dir, disk: [
    ["mkfs.fat", "-v", "-F32", "-n", "BOOT", disk + "p1"],
]

perms = {
    "/etc/": ["0", "0", "755"],
    "/usr/bin/resizefs": ["0", "0", "755"],
    "/usr/bin/zswap-arm-ctrl": ["0", "0", "755"],
    "/usr/bin/oemcleanup": ["0", "0", "755"],
    "/etc/polkit-1/rules.d": ["0", "0", "750"],
    "/etc/sudoers.d": ["0", "0", "750"],
    "/usr/lib": ["0", "0", "755"],
    "/usr/bin": ["0", "0", "755"],
    "/usr": ["0", "0", "755"],
    "/usr/bin/remove-calamares": ["0", "0", "755"],
    "/home/bred/": ["1001", "1001", "750"],
    "/home": ["0", "0", "755"],
}

mkcmds = """
copyfiles(config_dir + "/alarmimg", cfg["install_dir"])
fixperms(cfg["install_dir"])
pacstrap_packages(pacman_conf, cfg["packages_file"], cfg["install_dir"])
machine_id()
fixperms(cfg["install_dir"])
copy_skel_to_users()
logging.info("Partitioning rpi")
rootfs_size = int(
    subprocess.check_output(["du", "-s", "--exclude=proc", cfg["install_dir"]])
    .split()[0]
    .decode("utf-8")
)
img_size, ldev = makeimg(
    rootfs_size, cfg["fs"], cfg["img_name"], cfg["img_backend"]
)
partition(
    ldev, cfg["fs"], img_size, cfg["partition_table"](img_size, cfg["fs"])
)
if not os.path.exists(mnt_dir):
    os.mkdir(mnt_dir)
subprocess.run("mount " + ldev + "p1 " + mnt_dir + "/boot", shell=True)
copyfiles(cfg["install_dir"], mnt_dir, retainperms=True)
with open(mnt_dir + "/boot/cmdline.txt", "w") as f:
    root_uuid = get_fsline(ldev + "p2")
    f.write("root=" + root_uuid + " " + cmdline)
with open(work_dir + "/mnt/boot/config.txt", "a") as f:
    f.write(configtxt)
create_fstab(cfg["fs"], ldev)
unmount(cfg["img_backend"], mnt_dir, ldev)
cleanup(cfg["img_backend"])
if args.no_compress:
    copyimage(cfg["img_name"])
else:
    compressimage(cfg["img_name"])
cleanup(cfg["work_dir"])
"""
