#! /usr/bin/env python
from time import strftime

img_version = strftime("%Y-%m-%d")
edition = ""
device = "rock5b"  # rpi more will be added soon
arch = "aarch64"  # aarch64, armv7h
img_name = "BredOS-ARM-rock5b-" + img_version
install_dir = "arch"
fs = "ext4"  # ext4 or btrfs
img_type = "image"  # image (img.xz) or rootfs (tar.gz)
img_backend = "loop"  # loop or qemu-nbd

# If you use btrfs you need add `rootflags=subvol=@ rootfstype=btrfs`
# And remove `rootfstype=ext4`

cmdline = "earlycon=uart8250,mmio32,0xfeb50000 console=ttyFIQ0 console=tty1 consoleblank=0 loglevel=0 panic=10 rootwait rw init=/sbin/init rootfstype=ext4 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1 irqchip.gicv3_pseudo_nmi=0 switolb=1 coherent_pool=2M"

configtxt = """label BredOS ARM
    kernel /vmlinuz-linux-rockchip-rk3588
    initrd /initramfs-linux-rockchip-rk3588.img
    devicetreedir /dtbs/
    fdtoverlays  /dtbs/rockchip/overlay/rk3588-uart7-m2.dtbo

"""

partition_table = lambda img_size, fs: {
    "uboot": ["0%", "16M", "16M", "NONE"],
    "boot": ["16M", "150M", "134M", "fat32"],
    "primary": ["150M", "100%", str(int(img_size / 1000) - 150) + "M", fs],
}

partition_extras = lambda config_dir, disk: [
    ["mkfs.fat", "-v", "-F32", "-n", "BOOT", disk + "p1"],
    ["dd", "if=" + config_dir + "idbloader.img", "of=" + disk, "bs=512", "seek=64"],
    ["dd", "if=" + config_dir + "u-boot.itb", "of=" + disk, "bs=512", "seek=16384"],
]
