#! /usr/bin/env python
from time import strftime

img_version = strftime("%Y-%m-%d")
edition = ""
device = "rock5b"  # rpi more will be added soon
arch = "riscv64"  # aarch64, armv7h
img_name = "BredOS-RISCV-mars-" + img_version
install_dir = "arch"
fs = "ext4"  # ext4 or btrfs
img_type = "image"  # image (img.xz) or rootfs (tar.gz)
img_backend = "loop"  # loop or qemu-nbd

# If you use btrfs you need add `rootflags=subvol=@ rootfstype=btrfs`
# And remove `rootfstype=ext4`

cmdline = "rw console=tty0 console=ttyS0,115200 earlycon rootwait stmmaceth=chain_mode:1"

configtxt = """label BredOS Risc-V
    kernel /vmlinuz-linux
    initrd /initramfs-linux.img
    fdtdir /dtbs/
"""

partition_table = lambda img_size, fs: {
    "uboot": ["0%", "16M", "16M", "NONE"],
    "boot": ["16M", "150M", "134M", "fat32"],
    "primary": ["150M", "100%", str(int(img_size / 1000) - 150) + "M", fs],
}

partition_extras = lambda config_dir, disk: [
    # ["mkfs.fat", "-v", "-F32", "-n", "BOOT", disk + "p1"],
    # ["dd", "if=" + config_dir + "idbloader.img", "of=" + disk, "bs=512", "seek=64"],
    # ["dd", "if=" + config_dir + "u-boot.itb", "of=" + disk, "bs=512", "seek=16384"],
    print()
]

perms = {
    "/etc/": ["0", "0", "755"],
    "/usr/bin/resizefs": ["0", "0", "755"],
    "/usr/bin/zswap-arm-ctrl": ["0", "0", "755"],
    "/usr/bin/oemcleanup": ["0", "0", "755"],
    "/etc/polkit-1/rules.d": ["0", "0", "750"],
    "/etc/sudoers.d": ["0", "0", "750"],
    "/usr/lib": ["0", "0", "755"],
    "/usr/bin": ["0", "0", "755"],
    "/usr": ["0", "0", "755"],
    "/home/bred/.config/autostart/org.bredos.bakery.desktop": ["1001", "1001", "755"],
    "/home/bred/Desktop/org.bredos.bakery.desktop": ["1001", "1001", "755"],
    "/home/bred/": ["1001", "1001", "750"],
    "/home": ["0", "0", "755"],
}
