#! /usr/bin/env python
from time import strftime

img_version = strftime("%Y-%m-%d")
edition = "Cinnamon"
arch = "riscv64"  # aarch64, armv7h, riscv64
img_name = "BredOS-riscv64-OPI-RV-" + img_version
install_dir = "arch"
fs = "btrfs"  # ext4 or btrfs
img_type = "image"  # image (img.xz) or rootfs (tar.gz)
img_backend = "loop"  # loop or qemu-nbd

# If you use btrfs you need add `rootflags=subvol=@ rootfstype=btrfs`
# And remove `rootfstype=ext4`

cmdline = "rw console=tty0 console=ttyS0,115200 earlycon rootwait stmmaceth=chain_mode:1 rootflags=subvol=@ rootfstype=btrfs"

configtxt = """
## /etc/default/u-boot - configuration file 

U_BOOT_IS_SETUP='true'

#U_BOOT_ALTERNATIVES="default recovery"
#U_BOOT_DEFAULT="l0"
#U_BOOT_PROMPT="1"
#U_BOOT_ENTRIES="all"
#U_BOOT_MENU_LABEL="BredOS"
U_BOOT_PARAMETERS="console=ttyS0,115200 console=tty1 console=both rootwait rw init=/sbin/init rootflags=subvol=@ rootfstype=btrfs"
#U_BOOT_ROOT=""
#U_BOOT_TIMEOUT="50"

# Device tree file (will be searched and copied to /boot if U_BOOT_COPY_DTB_TO_BOOT=true)
U_BOOT_FDT="jh7110-orangepi-rv.dtb"

# Device tree overlays
#U_BOOT_FDT_OVERLAYS=""

#U_BOOT_SYNC_DTBS="true"
U_BOOT_COPY_DTB_TO_BOOT="true"


 
"""

partition_table = lambda img_size, fs: {
    "uboot": ["0%", "32M", "32M", "NONE"],
    "boot": ["32M", "200M", "168M", "fat32"],
    "primary": ["200M", "100%", str(int(img_size / 1000) - 150) + "M", fs],
}

partition_suffix = lambda config_dir, disk: [
    ["mkfs.fat", "-v", "-F32", "-n", "BOOT", disk + "p1"],
    # ["dd", "if=" + config_dir + "bootinfo_sd.bin", "of=" + disk, "seek=0", "conv=notrunc"],
    # ["dd", "if=" + config_dir + "FSBL.bin", "of=" + disk, "seek=256", "conv=notrunc"],
    # ["dd", "if=" + config_dir + "u-boot-env-default.bin", "of=" + disk, "seek=768", "conv=notrunc"],
    # ["dd", "if=" + config_dir + "u-boot-opensbi.itb", "of=" + disk, "seek=1664", "conv=notrunc"],
]


perms = {
    "/etc/": ["0", "0", "755"],
    "/usr/bin/resizefs": ["0", "0", "755"],
    "/usr/bin/zswap-arm-ctrl": ["0", "0", "755"],
    "/usr/bin/oemcleanup": ["0", "0", "755"],
    "/etc/polkit-1/rules.d": ["0", "0", "750"],
    "/etc/sudoers.d": ["0", "0", "750"],
    "/usr/lib": ["0", "0", "755"],
    "/usr/bin": ["0", "0", "755"],
    "/usr": ["0", "0", "755"],
    "/home/bred/.config/autostart/org.bredos.bakery.desktop": ["1001", "1001", "755"],
    "/home/bred/Desktop/org.bredos.bakery.desktop": ["1001", "1001", "755"],
    "/home/bred/": ["1001", "1001", "750"],
    "/home": ["0", "0", "755"],
}

mkcmds = """
copyfiles(config_dir + "/alarmimg", cfg["install_dir"])
fixperms(cfg["install_dir"])
pacstrap_packages(pacman_conf, cfg["packages_file"], cfg["install_dir"])
machine_id()
fixperms(cfg["install_dir"])
copy_skel_to_users()
logging.info("Partitioning rock5b")
rootfs_size = int(
    subprocess.check_output(["du", "-s", "--exclude=proc", cfg["install_dir"]])
    .split()[0]
    .decode("utf-8")
)
img_size, ldev = makeimg(
    rootfs_size, cfg["fs"], cfg["img_name"], cfg["img_backend"]
)
partition(
    ldev, cfg["fs"], img_size, cfg["partition_table"](img_size, cfg["fs"])
)
if not os.path.exists(mnt_dir):
    os.mkdir(mnt_dir)
subprocess.run("mount " + ldev + "p1 " + mnt_dir + "/boot", shell=True)
copyfiles(cfg["install_dir"], mnt_dir, retainperms=True)
u_boot_update(mnt_dir, cfg["configtxt"])
create_fstab(cfg["fs"], ldev)
unmount(cfg["img_backend"], mnt_dir, ldev)
cleanup(cfg["img_backend"])
if args.no_compress:
    copyimage(cfg["img_name"])
else:
    compressimage(cfg["img_name"])
cleanup(cfg["work_dir"])
"""
