name: Build Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, ARM64, BredOS]

    strategy:
      matrix:
        image: [edge2-cinnamon-image, edge2-gnome-image, nova-image, nx5-image, opi5-image, opi5plus-image, r58s-image, r58x-4g-image, r58x-image, r58x-pro-image, radxa-zero3-image, rock4c-plus-image, rock5a-image, rock5b-image, vim4-gnome-image, vim4-plasma-image, rock5c-image, cpi4-image]

    steps:
      - name: Checkout Images
        uses: actions/checkout@v4
        with:
          path: images

      - name: Checkout mkimage
        uses: actions/checkout@v4
        with:
          repository: BredOS/mkimage
          path: mkimage

      - name: Install dependencies
        run: |
          sudo pacman -Sy --noconfirm --needed \
          python python-prettytable parted btrfs-progs \
          git wget arch-install-scripts unzip

      - name: Build Image
        run: |
          sudo python mkimage/mkimage.py -c images/${{ matrix.image }} -w ./work -o ./out

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.image }}
          path: out/*.img.xz
          retention-days: 7

      - name: Cleanup
        run: |
          sudo rm -rf ./out
          sudo rm -rf ./work

  release:
    needs: build
    runs-on: [self-hosted, ARM64, BredOS]

    steps:
      - name: Download Artifacts
        run: |
          # Fetch the list of artifacts using GitHub's REST API
          mkdir ./out/ && cd ./out/
          ARTIFACTS=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            "https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts")

          # Extract artifact names and IDs
          echo "$ARTIFACTS" | jq -r '.artifacts[] | .name + " " + (.id|tostring)' | while read -r ARTIFACT_NAME ARTIFACT_ID; do
            echo "Downloading $ARTIFACT_NAME"
            curl -s -L -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/${{ github.repository }}/actions/artifacts/$ARTIFACT_ID/zip" \
              --output "$ARTIFACT_NAME.zip"
          done

          # Extract artifacts
          for artifact in *.zip; do
            unzip -q "$artifact" 
          done

      - name: Set current date as tag name
        id: set_tag_name
        run: echo "TAG_NAME=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./out/*.img.xz
          tag_name: ${{ env.TAG_NAME }}
          draft: true
          prerelease: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Clean up
        run: |
          rm ./out/ -rf
